
# This file is a part of MRNIU/cmake-kernel
# (https://github.com/MRNIU/cmake-kernel).
#
# build.yml for MRNIU/cmake-kernel.

name: build

on: 
  - push
  - pull_request
  - release

env:
  BUILD_TYPE: Release

jobs:
  build_docs:
    name: Build and publish documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install doxygen
          pip3 install jinja2 Pygments

      - name: Build
        run: |
          cmake -S documentation -B build
          cmake --build build --target GenerateDocs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doxygen/html

  build_osx:
    runs-on: macos-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
        
      - name: setup toolchain
        shell: bash
        run: |
          brew install x86_64-elf-gcc
          brew tap riscv-software-src/riscv
          brew install riscv-tools

      - name: make build dir
        shell: bash
        run: |
          mkdir ${{github.workspace}}/build

      - name: osx-i386
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -DTOOLCHAIN_PREFIX=x86_64-elf- -DCMAKE_C_COMPILER=x86_64-elf-gcc -DCMAKE_CXX_COMPILER=x86_64-elf-g++ -DARCH=i386 -DCMAKE_BUILD_TYPE=RELEASE -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 ..
          make
          rm -rf ./*

      - name: osx-x86_64
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -DTOOLCHAIN_PREFIX=x86_64-elf- -DCMAKE_C_COMPILER=x86_64-elf-gcc -DCMAKE_CXX_COMPILER=x86_64-elf-g++ -DARCH=x86_64 -DCMAKE_BUILD_TYPE=RELEASE -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 ..
          make
          rm -rf ./*

      - name: osx-riscv64
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -DTOOLCHAIN_PREFIX=riscv64-unknown-elf- -DCMAKE_C_COMPILER=riscv64-unknown-elf-gcc -DCMAKE_CXX_COMPILER=riscv64-unknown-elf-g++ -DARCH=riscv64 -DCMAKE_BUILD_TYPE=RELEASE -DHAVE_FLAG_SEARCH_PATHS_FIRST=0 ..
          make
          rm -rf ./*

  build_ubuntu:
    runs-on: ubuntu-latest
    needs: [build_osx]
    steps:
    - name: get code
      uses: actions/checkout@v2
      
    - name: setup toolchain
      shell: bash
      run: |
        sudo apt-get install -y gcc-riscv64-linux-gnu g++-riscv64-linux-gnu

    - name: make build dir
      shell: bash
      run: |
        mkdir ${{github.workspace}}/build

    - name: ubuntu-i386
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake -DTOOLCHAIN_PREFIX= -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DARCH=i386 -DCMAKE_BUILD_TYPE=RELEASE ..
        make
        rm -rf ./*

    - name: ubuntu-x86_64
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake -DTOOLCHAIN_PREFIX= -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DARCH=x86_64 -DCMAKE_BUILD_TYPE=RELEASE ..
        make
        rm -rf ./*

    - name: ubuntu-riscv64
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: |
        cmake -DTOOLCHAIN_PREFIX=riscv64-linux-gnu- -DCMAKE_C_COMPILER=riscv64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=riscv64-linux-gnu-g++ -DARCH=riscv64 -DCMAKE_BUILD_TYPE=RELEASE ..
        make
        rm -rf ./*
